### PR TITLE
Added a new helper method to get inherited properties.

### PR DESCRIPTION
**Pull request by homestar9**
When an object extends another object, it inherits the base object's properties.  When getting a memento, it should include any inherited properties by default.  However, if you specify `*` as the `defaultIncludes` it won't include any inherited properties.  Therefore, to fix this issue, I wrote a helper function that will traverse an object's metadata and grab all inherited properties.

### CODE REVIEW

**Comment by lmajano** [comment]
@homestar9 This looks great! 🥇  However, can you add the appropriate tests for it pretty please :)

**Comment by homestar9** [comment]
I had a dream you would say that! ;)  I'll take a stab at creating a test, however I may need some assistance because the test will need a mock object that will inherit properties from another mocked base object.  I haven't done that in Testbox before so this will be new to me.

**Comment by lmajano** [comment]
Jeje you know it was coming!!! Actually don’t mock it. Actually use the models in the test harness and build an inheritance chain

**Comment by homestar9** [comment]
Unfortunately, I ran into a little snag.  I couldn't figure out how to get a local instance of the project running on my machine.

Here's what I tried:
1. Forked the repo and cloned it into a directory on my computer `/repositories/mementifier/`
2. I noticed there was no server.json file in the project root, but I saw a few different json files in the `test-harness` folder so I assumed that was supposed to be the actual web root.  I picked `server-adobe@2016.json` and renamed it `server.json`.
3. I fired up commandbox and typed `box install` to install any dependencies indicated in `box.json`
5. I executed `server start` and an instance of ACF 2016 started up.

However, the browser showed the following error: `Could not create connection to database server. Attempted reconnect 3 times. Giving up.`  I'm guessing that the repository requires some type of database server connection to work.

**Comment by lmajano** [comment]
@homestar9 I just updated the readme for instructions for testing. You can follow them now.

**Comment by homestar9** [comment]
Awesome! Thank you. I'll make another attempt.

**Comment by myleslee** [comment]
@homestar9 How's your next attempt going? :)

**Comment by homestar9** [comment]
@myleslee, it went well thank you.  The pull request hasn't been merged yet but all work is complete here: https://github.com/coldbox-modules/mementifier/pull/9

**Pull request closed without merging**
